# Generated by Django 4.2.7 on 2023-11-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('userName', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('color', models.CharField(max_length=255)),
                ('tags', models.ManyToManyField(to='polygonbuilderapi.tag')),
            ],
        ),
    ]
